---
permalink: san-host/concept_vmware_esxi_host_remediation.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, esxi, host, remediation 
summary: 'Si utiliza 7-Mode Transition Tool \(7MTT\) para pasar de un sistema operativo Data ONTAP en 7-Mode a Clustered Data ONTAP en un entorno SAN, debe realizar una serie de pasos en sus hosts VMware ESXi antes de la transición a Data ONTAP. Debe apagar los hosts antes de la transición y debe realizar otra serie de pasos después de la transición para poder empezar a prestar servicio a los datos.' 
---
= Corrección de hosts VMware ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utiliza 7-Mode Transition Tool (7MTT) para pasar de un entorno SAN que funciona Data ONTAP en 7-Mode a Clustered Data ONTAP, debe realizar una serie de pasos en sus hosts VMware ESXi antes de la transición a Data ONTAP. Debe apagar los hosts antes de la transición y debe realizar otra serie de pasos después de la transición para poder empezar a prestar servicio a los datos.

*Información relacionada*

xref:task_testing_transitioned_luns_and_esxi_host_applications_before_cutover.adoc[Prueba de la transición de LUN y aplicaciones host ESXi antes de la fase de transición de las transiciones basadas en copias]

xref:concept_post_transition_requirements_for_esxi_hosts.adoc[Requisitos de la corrección posterior a la transición para hosts ESXi]
