---
permalink: san-host/concept_transitioning_luns_with_mount_points_using_dmmp_alias_names.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, lun, mount, points, dmmp, alias, names 
summary: Cuando realice la transición de una LUN con un punto de montaje con un nombre de alias, debe realizar pasos específicos para preparar la fase de transposición y debe volver a montar las LUN después de la transición. 
---
= Transición de LUN con puntos de montaje mediante nombres de alias DMMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando realice la transición de una LUN con un punto de montaje con un nombre de alias, debe realizar pasos específicos para preparar la fase de transposición y debe volver a montar las LUN después de la transición.

*Información relacionada*

xref:task_preparing_for_cutover_when_transitioning_luns_with_mounts_using_dmmp_aliases_on_linux_hosts.adoc[Preparación de la fase de transición al realizar la transición de las LUN con puntos de montaje mediante nombres de dispositivos DMMP en hosts Linux]

xref:task_remounting_luns_with_mount_point_using_dmmp_alias_name_on_linux_hosts_after_transition.adoc[Montaje de los LUN con puntos de montaje mediante nombres de alias DMMP en hosts Linux después de la transición]
