---
permalink: san-host/task_testing_dmmp_devices_on_rhel_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, dmmp, file, systems, rhel, cutover, copy, based 
summary: 'Si utiliza 7-Mode Transition Tool \(7MTT\) 2.2 o posterior y Data ONTAP 8.3.2 o posterior para realizar la transición del host Red Hat Enterprise Linux \(RHEL\) 5, Puede probar las LUN de Clustered Data ONTAP convertidas para verificar que puede conectar el host y las aplicaciones antes de la fase de transición. El host de origen puede seguir ejecutando I/o en sus LUN de 7-Mode de origen durante las pruebas.' 
---
= Prueba de dispositivos DMMP sin sistemas de archivos en hosts RHEL antes de la fase de transposición de transiciones basadas en copias
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utiliza 7-Mode Transition Tool (7MTT) 2.2 o posterior y Data ONTAP 8.3.2 o posterior para realizar la transición del host Red Hat Enterprise Linux (RHEL) 5, Puede probar las LUN de Clustered Data ONTAP convertidas para verificar que puede conectar el host y las aplicaciones antes de la fase de transición. El host de origen puede seguir ejecutando I/o en sus LUN de 7-Mode de origen durante las pruebas.

Sus nuevas LUN de Clustered Data ONTAP deben asignarse a su host de prueba y sus LUN deben estar listos para la transición.

Debe mantener la paridad del hardware entre el host de prueba y el host de origen, y debe realizar los siguientes pasos en el host de prueba.

Sus LUN de Clustered Data ONTAP se encuentran en modo de lectura/escritura durante las pruebas. Cuando finaliza la prueba y se prepara para la fase de transposición, se convierten al modo de solo lectura.

.Pasos
. Una vez finalizada la copia de datos de referencia, seleccione *modo de prueba* en la interfaz de usuario (UI) de 7MTT.
. En la interfaz de usuario de 7MTT, haga clic en *Apply Configuration*.
. Vuelva a analizar las LUN nuevas de Data ONTAP en clúster en el host de prueba:
+
`*rescan-scsi-bus.sh*`

. Obtenga los nombres de dispositivo SCSI nuevos para las LUN de Clustered Data ONTAP:
+
`*sanlun lun show*`

+
En el siguiente ejemplo: `/dev/sdl` Es el nombre del dispositivo SCSI para `lun_dmmp_raw` LUN y. `/dev/sdk` Es el nombre del dispositivo SCSI para `lun_dmmp_raw_alias` LUN:

+
[listing]
----
[root@ibmx3550-229-108 /]# sanlun lun show
controller(7mode/E-Series)/
vserver (cDOT/FlashRay lun-pathname   filename
------------------------------------------------------------------------
vs_brb   /vol/dmmp_raw_vol/lun_dmmp_raw             /dev/sdl
vs_brb   /vol/dmmp_raw_alias_vol/lun_dmmp_raw_alias	/dev/sdk
----
. Obtenga los identificadores de controlador de dispositivo (WWID) para las LUN de Data ONTAP en clúster:
+
`*/sbin/scsi_id -g-u-s /block/__SCSI_device_name__*`

+
A continuación se muestra un ejemplo de un WWID: "'3600a09804d532d79565d47617679764d'"

. Compruebe si se ha definido un alias en `/etc/multipath.conf` en el host de origen.
. Si hay un alias definido en el host de origen, añada el alias al `/etc/multipath.conf` File en el host de prueba, pero sustituya el identificador de dispositivo de 7-Mode por el ID de LUN de Clustered Data ONTAP.
. Actualice la configuración del alias de DMMP:
+
`*multipath*`

. Compruebe que el nombre del alias DMMP hace referencia correctamente a la LUN de Clustered Data ONTAP:
+
`*multipath -ll*`

. Realice las pruebas según sea necesario.
. Después de completar la prueba, apague el host de prueba:
+
`*shutdown -h -t0 now*`

. En la interfaz de usuario de 7MTT, haga clic en *Finalizar prueba*.


Si va a volver a asignar las LUN de Clustered Data ONTAP al host de origen, debe preparar el host de origen para la fase de transposición. Si van a seguir asignando sus LUN de Clustered Data ONTAP al host de prueba, no será necesario realizar otros pasos en el host de prueba.

*Información relacionada*

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[Recopilación de información previa a la transición del libro de trabajo de evaluación de inventario]

xref:task_verifying_that_rhel_luns_are_ready_for_transition_using_inventory_assessment_workbook.adoc[Comprobación de que las LUN de RHEL están listas para la transición mediante el manual de evaluación de inventario]

xref:task_preparing_for_cutover_when_transitioning_linux_host_dmmp_device_without_file_system.adoc[Preparación de la transición al realizar la transición de un dispositivo DMMP de host Linux sin un sistema de archivos]
