---
permalink: san-host/task_preparing_windows_hosts_for_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, windows, host 
summary: Hay pasos que debe realizar antes de pasar hosts de Windows de Data ONTAP en 7-Mode a Clustered Data ONTAP. 
---
= Preparar hosts de Windows para la transición
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay pasos que debe realizar antes de pasar hosts de Windows de Data ONTAP en 7-Mode a Clustered Data ONTAP.

Este procedimiento se aplica a las transiciones basadas en copias y a las transiciones sin copias.


NOTE: Si utiliza Windows 2003, debe actualizar a Windows 2008. La herramienta de corrección de host (TRH) no es compatible con Windows 2003 y necesita Windows 2008 o posterior para funcionar correctamente.

.Pasos
. Identificar los números de serie de LUN, los ID de LUN y los números de disco físico de Windows correspondientes de las LUN que se van a realizar la transición.
+
** Si el sistema ejecuta DSM de Data ONTAP, utilice el complemento de extensión de administración DSM de Data ONTAP (accesible a través del Administrador de servidores o el `get-sandisk` Cmdlet de PowerShell de Windows).
** Si el sistema está ejecutando MSDSM, utilice la herramienta de recopilación de inventario (ICT).


. Preparar para que las LUN sean visibles para el host una vez completada la transición.
+
** Si las LUN que se están realizando la transición son LUN FC o FCoE, cree o modifique la división en zonas estructural.
** Si las LUN que se están realizando la transición son LUN iSCSI, cree sesiones iSCSI que se conecten a la controladora de Clustered Data ONTAP.


. Utilice las TIC para generar el libro de trabajo de evaluación de inventario.


*Información relacionada*

https://["Configuración de SAN"]
