---
permalink: san-host/task_testing_transitioned_luns_on_aix_hosts_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, lun, aix, cutover, phase, copy, based, test 
summary: 'Si utiliza la herramienta de transición de 7-Mode \(7MTT\) 2.2 o una versión posterior y Data ONTAP 8.3.2 o posterior para realizar la transición de los LUN del host AIX, puede probar las LUN de Clustered Data ONTAP convertidas para verificar que puede montar el dispositivo MPIO antes de la fase de transición. El host de origen puede seguir ejecutando I/o en sus LUN de 7-Mode de origen durante las pruebas.' 
---
= Prueba de que ha realizado la transición de LUN en hosts AIX antes de la fase de transición de las transiciones basadas en copias
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utiliza la herramienta 7-Mode Transition Tool (7MTT) 2.2 o posterior y Data ONTAP 8.3.2 o posterior para realizar la transición de los LUN de host AIX, puede probar las LUN de Data ONTAP almacenadas en clúster para verificar que puede montar el dispositivo MPIO antes de la fase de transición. El host de origen puede seguir ejecutando I/o en sus LUN de 7-Mode de origen durante las pruebas.

Sus LUN deben estar preparadas para la transición.

Debe mantener la paridad del hardware entre el host de prueba y el host de origen, y debe realizar los siguientes pasos en el host de prueba.

Sus LUN de Clustered Data ONTAP se encuentran en modo de lectura/escritura durante las pruebas. Cuando finaliza la prueba y se prepara para la fase de transposición, se convierten al modo de solo lectura.

.Pasos
. Una vez finalizada la copia de datos de línea base, seleccione *modo de prueba* en la interfaz de usuario (UI) de 7MTT.
. En la interfaz de usuario de 7MTT, haga clic en *Apply Configuration*.
. En el host de prueba, vuelva a analizar las nuevas LUN de Data ONTAP en clúster:
+
`*cfgmgr*`

. Compruebe que hay presentes sus nuevas LUN de Clustered Data ONTAP:
+
`*sanlun lun show*`

. Verifique el estado del grupo de volúmenes:
+
`*lsvg vg_name*`

. Monte cada uno de los volúmenes lógicos:
+
`*mount -o log/dev/loglv00 _file_system_mount_point_*`

. Compruebe los puntos de montaje:
+
`*df*`

. Realice las pruebas según sea necesario.
. Apague el host de prueba:
+
`*shutdown -h*`

. En la interfaz de usuario de 7MTT, haga clic en *Finalizar prueba*.


Si va a volver a asignar las LUN de Clustered Data ONTAP al host de origen, debe preparar el host de origen para la fase de transposición. Si van a seguir asignando sus LUN de Clustered Data ONTAP al host de prueba, no será necesario realizar otros pasos en el host de prueba.
