---
permalink: san-host/task_preparing_for_cutover_when_transitioning_aix_data_luns_with_file_systems.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, cutover, phase, aix, data, lun 
summary: Si va a realizar la transición de un LUN de datos del host AIX con un sistema de archivos desde Data ONTAP que funciona en 7-Mode a Clustered Data ONTAP, debe realizar determinados pasos antes de introducir la fase de transposición. 
---
= Preparación de la fase de transición al realizar la transición de LUN de datos de host de AIX con sistemas de archivos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si va a realizar la transición de un LUN de datos del host AIX con un sistema de archivos desde Data ONTAP que funciona en 7-Mode a Clustered Data ONTAP, debe realizar determinados pasos antes de introducir la fase de transposición.

Debe establecerse la conectividad estructural y la división en zonas en los nodos de Clustered Data ONTAP.

Para las transiciones basadas en copias, realice estos pasos después de completar el funcionamiento de transición del almacenamiento en la herramienta de transición de 7-Mode. Las transiciones sin copias no son compatibles con los hosts AIX.

.Pasos
. Detenga la I/o en todos los puntos de montaje.
. Apague cada aplicación que acceda a las LUN de acuerdo con las recomendaciones del proveedor de aplicaciones.
. Desmonte todos los puntos de montaje:
+
`*umount _mount_point_*`

. Deshabilite el grupo de volúmenes:
+
`*varyoffvq _vg_name_*`

. Exporte el grupo de volúmenes:
+
`*exportvg _vg_name_*`

. Verifique el estado del grupo de volúmenes:
+
`*lsvg*`

+
El grupo de volúmenes exportado no debe aparecer en la salida.

. Si hay entradas obsoletas, quítelas:
+
`*rmdev -Rdl hdisk#*`


