---
permalink: copy-based/concept_considerations_for_local_users_and_groups_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, cifs, local, users, groups 
summary: Debe tener en cuenta las consideraciones que se deben tener en cuenta para ejecutar las operaciones de transición al migrar los grupos y usuarios locales CIFS. 
---
= Consideraciones para la transición de usuarios y grupos locales CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener en cuenta las consideraciones que se deben tener en cuenta para ejecutar las operaciones de transición al migrar los grupos y usuarios locales CIFS.

* Si el clúster de destino ejecuta Clustered Data ONTAP 8.2, no se debe intentar realizar la transición en los volúmenes de 7-Mode que están sirviendo datos CIFS y a los que acceden los usuarios y grupos locales.
+
La herramienta de transición de 7-Mode no admite la transición de usuarios y grupos locales a Clustered Data ONTAP 8.2.

* No se admite la transición de volúmenes que sirven datos CIFS desde una controladora de 7-Mode o una unidad vFiler con usuarios y grupos locales a una SVM que tiene grupos y usuarios locales CIFS que no son BUILTIN.
+
La SVM debe tener solo grupos y usuarios locales BUILTIN CIFS para la transición.

+
Mientras se realiza la transición de usuarios y grupos locales de una controladora de 7-Mode específica o una unidad vFiler a una SVM específica, se realiza la transición de los grupos y usuarios locales del primer proyecto de transición. En la transición posterior de proyectos con la misma controladora de 7-Mode o unidad vFiler a la misma SVM, se ignora la transición de usuarios y grupos locales, aunque la transición se completa correctamente. El nombre del usuario local en el sistema 7-Mode no debe ser igual al nombre del servidor CIFS en la SVM.

* Debe conocer los límites del número de usuarios locales y grupos compatibles con Clustered Data ONTAP 8.2.1 y versiones posteriores.
* Una cuenta de usuario local con una contraseña vacía o cuentas de usuario local con contraseñas que contienen más de 14 caracteres en el sistema 7-Mode se realiza la transición al software ONTAP con la contraseña `*cifsUser@1*`.
+
Una vez finalizada la transición, puede acceder a estos usuarios desde el sistema Windows mediante la contraseña `*cifsUser@1*`. A continuación, debe cambiar manualmente la contraseña de tales usuarios locales CIFS en la SVM mediante el siguiente comando:

+
`*cifs users-and-groups local-user set-password -vserver _svm_name_ -user-name _user_name_*`.

* Si no es posible acceder a la dirección IP de la herramienta de transición de 7-Mode desde el software ONTAP de destino, la herramienta de transición de 7-Mode bloquea la transición de los usuarios y grupos locales CIFS al software ONTAP durante la fase de comprobaciones previas. Si observa este error durante la fase comprobaciones previas, utilice
+
`*network ping -node local -destination _ip_address_*`

+
Para garantizar que es posible acceder a la dirección IP de 7-Mode Transition Tool desde el software ONTAP de destino. Puede editar el `\etc\conf\transition-tool.conf` Archivo que se instala con 7-Mode Transition Tool para modificar cualquier opción de configuración que utilice la herramienta, como la dirección IP de 7-Mode Transition Tool.

* La SVM a la que se realizan la transición de los usuarios y grupos locales debe tener una LIF de datos.
* Si un grupo local tiene varios identificadores de sistema miembros (SID) asignados a un único usuario o grupo de dominio en el sistema 7-Mode, la herramienta de transición de 7-Mode bloquea la transición de usuarios y grupos locales a ONTAP durante la fase de comprobaciones previas.
+
Si observa este error durante la fase comprobaciones previas, debe quitar manualmente los SID adicionales asignados a un único usuario o grupo de dominio en el sistema 7-Mode. A continuación, debe volver a ejecutar la operación de comprobaciones previas con un único SID asignado al usuario o grupo de dominio.

+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Troubleshooting_Workflow%3A_CIFS%3A_Device_attached_to_the_system_is_not_functioning["Flujo de trabajo de solución de problemas: CIFS: El dispositivo conectado al sistema no funciona"]



*Información relacionada*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html["Gestión de SMB/CIFS"]
