---
permalink: copy-based/concept_considerations_for_transitioning_of_snaplock_compliance_volumes.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, snaplock, compliance, volumes 
summary: La herramienta de transición de 7-Mode admite la transición de los volúmenes de SnapLock Compliance independientes y los volúmenes de SnapLock Compliance que se encuentran en una relación de SnapMirror. 
---
= Consideraciones para la transición de volúmenes de cumplimiento de SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La herramienta de transición de 7-Mode admite la transición de los volúmenes de SnapLock Compliance independientes y los volúmenes de SnapLock Compliance que se encuentran en una relación de SnapMirror.

El flujo de trabajo para realizar la transición de volúmenes de cumplimiento de normativas de SnapLock independientes es el mismo que para realizar la transición de volúmenes de FlexVol.

La transición de relaciones de SnapMirror para volúmenes de cumplimiento de normativas de SnapLock no se automatiza en la herramienta de transición de 7-Mode. Es necesario realizar la transición de los volúmenes primario y secundario de SnapLock Compliance como volúmenes independientes y, luego, volver a sincronizar manualmente las relaciones.

Puede incluir los volúmenes de cumplimiento SnapLock (tanto independientes como secundarios en relaciones de SnapMirror) como un volumen independiente en proyectos independientes, primarios y secundarios.

El modo de lectura/escritura previa no se admite en proyectos con volúmenes de cumplimiento de SnapLock. Se recomienda crear proyectos independientes para volúmenes de cumplimiento SnapLock y volúmenes que no sean de SnapLock Compliance, ya que no se admite el modo de lectura/escritura previo si se incluyen volúmenes de SnapLock Compliance en el proyecto.

Durante la operación de transposición, si el volumen seleccionado es un volumen de cumplimiento de SnapLock y es el destino de una relación de SnapMirror, la relación de SnapMirror entre el volumen de 7-Mode y el volumen ONTAP se elimina sin la operación de interrupción de SnapMirror. Con esta acción, los volúmenes secundarios de cumplimiento de normativas de ONTAP SnapLock pueden permanecer en modo de solo lectura. Los volúmenes secundarios de cumplimiento de normativas de ONTAP SnapLock deben estar en modo de solo lectura para que la operación de resincronización se complete correctamente entre los volúmenes primario y secundario de cumplimiento de normativas de SnapLock.

Consulte https://["Cómo realizar la transición de los volúmenes de 7-Mode SnapLock Compliance con una relación de SnapMirror a Data ONTAP en clúster"]
