---
permalink: install-admin/concept_system_requirements_for_7mtt_on_windows.html 
sidebar: sidebar 
keywords: ontap, 7, mode, install, system, requirements, windows, transition, tool 
summary: Debe asegurarse de que el host de Windows cumpla con la configuración necesaria para instalar y ejecutar la herramienta 7-Mode Transition Tool. 
---
= Requisitos del sistema para instalar la herramienta 7-Mode Transition Tool en sistemas Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe asegurarse de que el host de Windows cumpla con la configuración necesaria para instalar y ejecutar la herramienta 7-Mode Transition Tool.

Asegúrese de consultar la herramienta de transición actual de 7-Mode link:http://docs.netapp.com/us-en/ontap-7mode-transition/releasenotes.html["Notas de la versión"] para obtener la información más reciente sobre los hosts compatibles y los problemas conocidos.



== Requisitos de hardware

* Procesador x64 de doble núcleo, 1.0 GHz o más
* 8 GB DE MEMORIA RAM
* 40 GB de espacio libre en disco




== Requisitos de software

* El sistema Windows de 64 bits debe ejecutar una de las siguientes versiones del sistema operativo:
+
** Windows 7 Enterprise
** Windows 7 Enterprise SP1
** Windows Server 2008 Standard
** Windows Server 2008 R2 Standard
** Windows Server 2008 R2 Enterprise con SP1
** Windows Server 2012 Standard
** Windows Server 2012 R2 Standard
** Windows 8.1 Enterprise
** Windows Server 2012 R2 Datacenter Edition
** En el caso de la herramienta de transición de 7-Mode, versión 3.3.2P1, también puede utilizar una de las siguientes versiones de sistema operativo:
+
*** Windows 10 Enterprise
*** Windows Server 2016 Standard
*** Centro de datos Windows Server 2016
*** Windows Server 2019 Standard
*** Centro de datos Windows Server 2019


** Para 7-Mode Transition Tool versión 3.3.3, también se puede usar una de las siguientes versiones de sistemas operativos:
+
*** Windows 10 Professional
+

NOTE: Puede utilizar una máquina virtual de Windows que cumpla los requisitos de software y de hardware necesarios para instalar la herramienta 7-Mode Transition Tool.





* Actualización 1.8 de Oracle Java Runtime Environment (JRE) de 64 bits 331
+

NOTE: Si el host de Windows no tiene JRE o tiene instalado un JRE de 32 bits, el instalador de 7-Mode Transition Tool instala automáticamente la actualización 331 de JRE 1.8 de 64 bits. Si se ha instalado una versión anterior de JRE de 64 bits, el instalador actualiza automáticamente JRE a la actualización 331 de JRE 1.8.

+
Cuando JRE se actualiza automáticamente, el resto de aplicaciones que requieren versiones anteriores de JRE pueden verse afectadas.

+

NOTE: Con JRE versiones 1.8 Update 46 o posterior (incluido JRE 1.8 actualización 331) para que la herramienta de transición de 7-Mode se comunique con Data ONTAP en sistemas 7-Mode y sistemas ONTAP, la longitud de la clave SSL en los sistemas Data ONTAP que funcionan en 7-Mode y los sistemas ONTAP debe ser, al menos, 1024.

+
https://["7MTT: Cómo resolver un problema de comunicación TLS o SSL"]





== Requisitos de configuración del servidor

Para acceder a la interfaz Web, el sistema Windows en el que se instala la herramienta debe configurarse de la siguiente manera:

* El puerto 8443 del servidor de 7-Mode Transition Tool debe estar disponible.
+
Si el puerto 8443 no está disponible o si desea utilizar un puerto diferente, debe cambiar el puerto especificado por el `tool.https.port` en la `$INSTALL_DIR\etc\conf\transition-tool.conf` archivo.

+
La práctica recomendada es usar HTTPS para acceder a la interfaz web. Sin embargo, si desea utilizar HTTP para acceder a la interfaz web, debe estar disponible el puerto 8088. Para una alternativa al puerto 8088, debe cambiar el puerto especificado por el `tool.http.port` en la `transition-tool.conf` archivo.

+

NOTE: Debe reiniciar el servicio 7-Mode Transition Tool después de cambiar el puerto en el archivo de configuración.

* El firewall debe estar desactivado o configurado para permitir el tráfico en el puerto que se utiliza para acceder a la herramienta.


Para realizar la transición de grupos de redes y usuarios y grupos locales CIFS, se deben cumplir los siguientes requisitos:

* El puerto 8088 de la herramienta de transición de 7-Mode debe estar disponible.
+
Para una alternativa al puerto 8088, debe cambiar el puerto especificado por el `tool.http.port` en la `transition-tool.conf` File y, a continuación, reinicie el servicio 7-Mode Transition Tool.

* Cada nodo del clúster debe tener al menos un LIF de datos configurado para la SVM de destino.
* Todos los LIF de datos de SVM deben poder comunicarse con el puerto 8088 de 7-Mode Transition Tool o con el puerto especificado por el `tool.http.port` en la `transition-tool.conf` archivo.
+

NOTE: Debe asegurarse de que los cortafuegos no bloqueen este tráfico.





== Requisitos del cliente (interfaz web)

El sistema que accede a la interfaz web debe tener lo siguiente:

* Uno de los siguientes exploradores web:
+
** Microsoft Internet Explorer 9, 10 o 11
** Google Chrome 27 o posterior
** Mozilla Firefox 20 o posterior todos los navegadores deben estar habilitados para TLS.


+

NOTE: Si está utilizando Microsoft Internet Explorer como explorador Web, debe deshabilitar SSLv2.

* Una resolución de pantalla de 1280 × 1024 o superior


Cada vez que instale una nueva versión de la herramienta, debe borrar la memoria caché del explorador pulsando Ctrl+F5 en el sistema.

*Información relacionada*

https://["Interoperabilidad de NetApp"]
