---
permalink: install-admin/task_uninstalling_7_mode_transition_tool_on_linux.html 
sidebar: sidebar 
keywords: ontap, 7, mode, install, uninstall, transition, tool, linux 
summary: Puede desinstalar la 7-Mode Transition Tool en Linux si utiliza la interfaz de línea de comandos. 
---
= Desinstalación de 7-Mode Transition Tool en Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desinstalar la 7-Mode Transition Tool en Linux si utiliza la interfaz de línea de comandos.

* Debe haber completado todas las transiciones en curso.
+

IMPORTANT: La instalación de una versión más reciente o la reinstalación de la misma versión de la herramienta no le permite acceder a las operaciones de transición iniciadas por la instancia desinstalada.

* Si se ejecuta la herramienta de transición de 7-Mode, es necesario detenerla.


JRE no se quita como parte de la desinstalación.

.Pasos
. Desinstale 7-Mode Transition Tool ejecutando el siguiente comando desde la ubicación en la que ha extraído la herramienta 7-Mode Transition Tool:
+
`*./unconfigure*`

. Quite el directorio de 7-Mode Transition Tool:
+
.. `*cd ..*`
.. `*rm -rf NetApp_7ModeTransitionTool*`






== Ejemplo

[listing]
----

bash-4.2# cd /root/Downloads/extracted_folder/NetApp_7ModeTransitionTool
bash-4.2# ./unconfigure
bash-4.2# cd ..
bash-4.2# rm -rf NetApp_7ModeTransitionTool
----