---
permalink: copy-free/concept_considerations_for_transitioning_unix_users_and_groups.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, netgroups, unix, users, groups 
summary: La configuración de netgroup se realiza la transición sólo si el archivo 7-Mode /etc/netgroup tiene un tamaño inferior a 5 MB. Los usuarios y grupos de UNIX se realizan la transición solo si el número total de usuarios y grupos de UNIX del SVM no supera los límites de usuarios y grupos en ONTAP. 
---
= Consideraciones sobre la transición de grupos de redes y usuarios y grupos UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuración de netgroup se realiza la transición sólo si el 7-Mode `/etc/netgroup` El archivo tiene un tamaño inferior a 5 MB. Los usuarios y grupos de UNIX se realizan la transición solo si el número total de usuarios y grupos de UNIX del SVM no supera los límites de usuarios y grupos en ONTAP.



== Consideraciones sobre los grupos de red

Si la `/etc/netgroup` El archivo en 7-Mode es superior a 5 MB, la configuración de netgroup no se realiza la transición. Debe realizar una de las siguientes acciones para continuar con la transición:

* Excluir la transición de netgroups.
+
xref:task_customizing_configurations_for_transition.adoc[Personalización de la transición de configuraciones de 7-Mode]

* Mueva la configuración de netgroup a servidores NIS o LDAP antes de realizar la transición.




== Consideraciones para usuarios y grupos de UNIX

Si el número total de usuarios y grupos de UNIX en transición supera el límite de usuarios y grupos de UNIX en ONTAP, la herramienta 7-Mode Transition Tool bloquea la transición. Debe realizar una de las siguientes acciones para continuar con la transición:

* Excluir la transición de usuarios y grupos UNIX.
+
xref:task_customizing_configurations_for_transition.adoc[Personalización de la transición de configuraciones de 7-Mode]

* Mueva los usuarios y grupos UNIX a servidores NIS o LDAP antes de realizar la transición.


*Información relacionada*

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html["Gestión de NFS"]
