---
permalink: copy-free/concept_considerations_for_space_when_transitioning_san_volumes.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, space, considerations, san, volumes 
summary: Debe asegurarse de que haya espacio suficiente disponible en los volúmenes durante la transición. Además del espacio necesario para almacenar datos y copias Snapshot, el proceso de transición también requiere 1 MB de espacio por LUN para actualizar ciertos metadatos del sistema de archivos. 
---
= Consideraciones de espacio cuando se realiza la transición de volúmenes SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe asegurarse de que haya espacio suficiente disponible en los volúmenes durante la transición. Además del espacio necesario para almacenar datos y copias Snapshot, el proceso de transición también requiere 1 MB de espacio por LUN para actualizar ciertos metadatos del sistema de archivos.

Puede utilizar el `df -h` Comando en el volumen de 7-Mode para verificar si el espacio libre de 1 MB por LUN está disponible en el volumen. El volumen también debe tener espacio libre equivalente a la cantidad de datos que se espera que se escriban en el volumen antes de que los hosts se encuentren en modo inactivo. Si el volumen no tiene suficiente espacio libre disponible, se debe añadir la cantidad de espacio necesaria al volumen de 7-Mode.

Si la transición falla durante la fase de importación por falta de espacio en el volumen, se genera el siguiente mensaje de EMS: `LUN.vol.proc.fail.no.space: Processing for LUNs in volume vol_name failed due to lack of space`.

Si hay volúmenes que contienen LUN reservadas para el espacio, es posible que el volumen crezca hasta 1 MB por LUN no proporcione espacio suficiente. En estos casos, la cantidad de espacio que se debe agregar es el tamaño de la reserva de Snapshot para el volumen. Después de agregar espacio al volumen, puede usar el `lun transition start` Comando para realizar la transición de las LUN.

*Información relacionada*

xref:task_recovering_from_a_failed_lun_transition.adoc[Recuperación de una transición de LUN en caso de error]

http://docs.netapp.com/ontap-9/index.jsp["Documentación de NetApp: ONTAP 9"]
