---
permalink: copy-free/concept_restrictions_during_preproduction_testing.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, preproduction, testing, restrictions 
summary: Algunas operaciones están bloqueadas y algunas no se recomiendan durante las pruebas de preproducción. Estas restricciones se imponen para permitir una reversión a 7-Mode si no desea confirmar la transición. 
---
= Restricciones durante la prueba de preproducción
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Algunas operaciones están bloqueadas y algunas no se recomiendan durante las pruebas de preproducción. Estas restricciones se imponen para permitir una reversión a 7-Mode si no desea confirmar la transición.



== Operaciones bloqueadas

|===
| Funcionamiento | Descripción 


 a| 
Eliminar automáticamente (eliminación automática) las copias Snapshot del agregado
 a| 
Como se requieren las copias de Snapshot a nivel de agregado de 7-Mode creadas durante la operación de exportación en caso de que se produzca una reversión, las copias de Snapshot no se eliminan automáticamente cuando crece el espacio usado en el agregado.


IMPORTANT: Deberá supervisar el espacio físico libre en el agregado y asegurarse de que los agregados no se quede sin espacio durante las pruebas.



 a| 
Mover volúmenes a otro agregado
 a| 
* No se pueden mover volúmenes a los agregados convertidos.
* Puede mover volúmenes del clúster de los agregados convertidos a agregados.




 a| 
Copiar o mover LUN entre volúmenes
 a| 
* No se pueden copiar ni mover LUN a los volúmenes convertidos.
* Puede copiar o mover LUN de los volúmenes convertidos a otros volúmenes del clúster.




 a| 
Creación de un agregado
 a| 
Esta operación está restringida en el par de alta disponibilidad del clúster de destino. Puede crear agregados en otros nodos en el clúster.



 a| 
Destruir un agregado
 a| 
Dado que las copias de Snapshot a nivel de agregado de 7-Mode creadas durante la operación de exportación se necesitan en caso de reversión, los agregados convertidos no se pueden destruir.



 a| 
Configuración de un agregado que ha realizado la transición como agregado raíz
 a| 
No se pueden seleccionar los agregados convertidos como agregados raíz. Además, no puede modificar la política de alta disponibilidad de los agregados convertidos a CFO.



 a| 
Ejecución de operaciones de copia de archivos
 a| 
* No se pueden mover ni copiar archivos (de una sola copia bajo demanda) en los volúmenes convertidos.
* Se pueden mover o copiar archivos de los volúmenes que han pasado a otros volúmenes del clúster.




 a| 
Reflejar un agregado existente
 a| 
La operación se bloquea en todos los agregados del clúster.



 a| 
Actualizar o revertir la versión de Data ONTAP en los nodos del clúster de destino
 a| 
Debe confirmar el proyecto antes de actualizar o revertir los nodos del clúster de destino.



 a| 
Adición de discos
 a| 
No puede ejecutar el `storage aggregate add-disks` en el nivel de privilegios de administrador. Sin embargo, puede ejecutar este comando en el nivel de privilegios avanzados.


IMPORTANT: Debe asegurarse de que se añadan exclusivamente los discos de repuesto de las bandejas de discos de 7-Mode para aumentar el espacio de los agregados convertidos. Debe añadir discos de repuesto con el `-disklist` parámetro (el `-diskcount` no se debe utilizar el parámetro).



 a| 
Designar un volumen que ha realizado la transición como volumen raíz de SVM
 a| 
No puede ejecutar el `volume make-vsroot` comando en los volúmenes convertidos.

|===


== Operaciones que no se recomiendan

|===
| Funcionamiento | Acción correctiva antes de la reversión 


 a| 
Reubicación de agregados

La propiedad del agregado que ha migrado se cambia a su partner de alta disponibilidad.
 a| 
Cambie la propiedad del agregado antes de la reversión debido a que la herramienta 7-Mode Transition Tool asigna los agregados a las controladoras de 7-Mode según la información de asignación de nodos de destino que se ha guardado en el proyecto.



 a| 
Crear volúmenes en los agregados convertidos
 a| 
Debe eliminar estos volúmenes o moverlos a diferentes agregados.



 a| 
Cambiar el nombre de los agregados o volúmenes
 a| 
Cambie el nombre de los agregados o los volúmenes a sus nombres originales.



 a| 
Cambiar el tipo de RAID
 a| 
El tipo de RAID debe coincidir con el tipo de RAID 7-Mode si decide revertir a 7-Mode.

|===
*Información relacionada*

http://["Comandos de ONTAP 9"]
