---
permalink: copy-free/reference_required_tools_and_documentation.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, tools, documentation, required 
summary: El Config Advisor es la herramienta necesaria para realizar la transición sin copias. Debe usar Config Advisor para verificar el cableado de las bandejas de discos. También hay disponible documentación adicional para la reparación de hosts SAN. 
---
= Herramientas y documentación necesarias para una transición sin copia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El Config Advisor es la herramienta necesaria para realizar la transición sin copias. Debe usar Config Advisor para verificar el cableado de las bandejas de discos. También hay disponible documentación adicional para la reparación de hosts SAN.



== Config Advisor

Deberá utilizar el perfil de ejecución «transición» de Config Advisor para comprobar el cableado una vez que las bandejas de discos de 7-Mode estén conectadas a los nodos del clúster de destino.

https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Descargas de NetApp: Config Advisor"]



== Documentación

Describe los pasos previos y posteriores a la transición que deben realizarse en hosts SAN cuando se realiza la transición usando una transición sin copias.

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-sanspl/home.html["Transición y corrección de hosts de SAN"]
