---
permalink: copy-free/task_transitioning_to_clustered_ontap_8_3_from_a_7_mode_version_with_32_bit_data.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, prepare, 32, aggregates 
summary: ONTAP 8.3 y versiones posteriores no admiten agregados, volúmenes y copias Snapshot de 32 bits. Por tanto, debe ampliar los agregados de 32 bits a 64 bits y, a continuación, buscar y eliminar cualquier volumen de 32 bits y las copias Snapshot del sistema 7-Mode antes de la transición. 
---
= Preparación para la transición de sistemas 7-Mode con agregados de 32 bits
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 8.3 y versiones posteriores no admiten agregados, volúmenes y copias Snapshot de 32 bits. Por tanto, debe ampliar los agregados de 32 bits a 64 bits y, a continuación, buscar y eliminar cualquier volumen de 32 bits y las copias Snapshot del sistema 7-Mode antes de la transición.

* *agregados de 32 bits*
+
.. xref:task_expanding_an_aggregate_to_64_bit_format_without_adding_storage.adoc[Ampliación de un agregado al formato de 64 bits]
.. xref:task_finding_and_removing_32_bit_data_from_source_volumes_and_snapshot_copies.adoc[Buscar y quitar volúmenes de 32 bits y copias Snapshot]


* *Volúmenes de 32 bits o copias Snapshot*
+
Aunque solo tenga agregados y volúmenes de 64 bits, pueden permanecer algunos volúmenes FlexVol o copias Snapshot de 32 bits o formato mixto. Debe eliminar estos volúmenes y las copias Snapshot antes de la transición.

+
xref:task_finding_and_removing_32_bit_data_from_source_volumes_and_snapshot_copies.adoc[Buscar y quitar volúmenes de 32 bits y copias Snapshot]



*Información relacionada*

http://www.netapp.com/us/media/tr-3978.pdf["Informe técnico de NetApp 3978: Ampliación in situ de agregados de 32 bits a información general y prácticas recomendadas de 64 bits"]
