---
permalink: copy-free/task_testing_workloads_and_applications.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, test, workload, application 
summary: Debe probar manualmente todas las cargas de trabajo y aplicaciones en el entorno de preproducción. A continuación, puede iniciar la producción durante un breve período de tiempo para evaluar si es necesario revertir antes de confirmar el proyecto. 
---
= Prueba de las cargas de trabajo y las aplicaciones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe probar manualmente todas las cargas de trabajo y aplicaciones en el entorno de preproducción. A continuación, puede iniciar la producción durante un breve período de tiempo para evaluar si es necesario revertir antes de confirmar el proyecto.

Los agregados que se han trasladado deben tener al menos un 5% de espacio físico libre.


NOTE: Lo mejor es disponer de al menos un 20% de espacio libre en los agregados convertidos.

Algunas operaciones están restringidas durante las pruebas de preproducción.

xref:concept_restrictions_during_preproduction_testing.adoc[Restricciones durante la prueba de preproducción]

.Pasos
. Conecte los clientes a los volúmenes en transición.
. Si tiene cargas de trabajo SAN, realice las tareas de corrección del host posteriores a la transición en los hosts SAN.
+
http://["Transición y corrección de hosts de SAN"]

. Pruebe todas las cargas de trabajo y aplicaciones que usan los datos y las configuraciones que se han trasladado.
. Compruebe que los agregados que han realizado la transición no se están quedando sin espacio supervisando el espacio físico libre en los agregados convertidos desde la pestaña Aggregates del panel de 7-Mode Transition Tool.
+
*Solución de problemas:* Si se queda sin espacio en los agregados convertidos, puede agregar discos.

+
.. Inicie sesión en el nivel de privilegio avanzado: +
`*set -privilege advanced*`
.. Seleccione los discos de repuesto de las bandejas de discos 7-Mode y añada discos para aumentar el espacio en los agregados convertidos: +
`*storage aggregate add-disks -aggregate _aggr_name_ -disklist _disk1_*`
+
Si los discos de reserva de 7-Mode no están disponibles, puede utilizar discos de reserva de las bandejas de discos en los nodos del clúster; sin embargo, al hacerlo se complica el proceso de reversión.





Puede empezar a servir datos de producción.

[IMPORTANT]
====
Puede servir datos en el entorno de producción durante un breve periodo para asegurarse de que las cargas de trabajo funcionan correctamente en un entorno de producción y no es necesario revertir a 7-Mode. No debe prolongar esta fase y no debe retrasar la confirmación del proyecto de transición sin copias por los siguientes motivos:

* La probabilidad de quedarse sin espacio en los agregados convertidos aumenta a medida que se escriben nuevos datos en los volúmenes.
* Durante la reversión, no estará disponible ningún dato nuevo escrito en los volúmenes durante este momento.


====
*Información relacionada*

xref:concept_reverting_a_copy_free_transition_project.adoc[Realizar una reversión de la transición a 7-Mode]

http://["Comandos de ONTAP 9"]
