---
permalink: copy-free/task_transitioning_primary_and_secondary_systems_of_a_snapmirror_relationship_in_parallel.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, primary, secondary, system, snapmirror, relationship, parallel 
summary: Puede realizar la transición de los pares de alta disponibilidad primario y secundario que contienen los volúmenes de una relación de SnapMirror de 7-Mode en paralelo. A continuación, debe configurar manualmente la relación de SnapMirror para volúmenes en Clustered Data ONTAP después de la transición. La relación de SnapMirror se mantiene después de la transición sin necesidad de volver a establecer la base. 
---
= Transición de sistemas principales y secundarios en una relación de SnapMirror en paralelo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar la transición de los pares de alta disponibilidad primario y secundario que contienen los volúmenes de una relación de SnapMirror de 7-Mode en paralelo. A continuación, debe configurar manualmente la relación de SnapMirror para volúmenes en Clustered Data ONTAP después de la transición. La relación de SnapMirror se mantiene después de la transición sin necesidad de volver a establecer la base.

Debe haber preparado los clústeres de origen y destino para realizar la transición de las relaciones de SnapMirror.

xref:task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.adoc[Preparación del clúster para la transición de relaciones de SnapMirror para volúmenes]

Debe realizar la transición de los pares de alta disponibilidad primario y secundario en la misma ventana de transposición.

.Pasos
. Desde la herramienta 7-Mode Transition Tool, realice una transición sin copias de los dos pares de alta disponibilidad que contienen los volúmenes primario y secundario de la relación de SnapMirror para volúmenes de 7-Mode.
+
Antes de realizar la transición de la pareja de alta disponibilidad 7-Mode que contiene los volúmenes secundarios, no se requiere ninguna intervención manual para las relaciones de SnapMirror de 7-Mode. Esto garantiza que los volúmenes secundarios 7-Mode se realice la transición como volúmenes de solo lectura a ONTAP.

+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[Transición de agregados de 7-Mode mediante la transición sin copias]

. Cree una relación entre iguales de SVM que contenga los volúmenes primario y secundario convertidos.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["Administración del sistema"]

. Cree una relación de SnapMirror para volúmenes entre los volúmenes primario y secundario convertidos.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-cg/home.html["Preparación exprés para la recuperación ante desastres de volúmenes"]

. En el volumen de destino, resincronice el volumen de origen y el volumen de destino de la relación de SnapMirror:
+
`*snapmirror resync*`

+

IMPORTANT: Debe haber al menos una copia Snapshot común entre los volúmenes de origen y de destino.

+
*Solución de problemas:* la resincronización de SnapMirror falla si se creó la copia snapshot común en una versión de Data ONTAP anterior a 8.1. Puede utilizar el `-fs-version` con el `volume snapshot show` Comando en el nivel de privilegio avanzado para ver la versión en la que se creó la copia Snapshot. Si tiene este problema, rompa la relación de SnapMirror y vuelva a realizar la resincronización.

. Supervise el estado de las transferencias de datos de SnapMirror:
+
`*snapmirror show*`

+

IMPORTANT: No debe realizar ninguna operación, como mover volúmenes o interrumpir SnapMirror, en los volúmenes de origen y destino hasta que la resincronización se haya realizado correctamente. Asegúrese de que la resincronización no se cancele y se complete correctamente; de lo contrario, los volúmenes pueden ir a un estado inconsistente.

. Confirmar la transición del proyecto secundario, seguido del proyecto principal.
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[Compromiso del proyecto de transición sin copias]



*Información relacionada*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandos de ONTAP 9"]

https://docs.netapp.com/us-en/ontap/["System Manager"]
