---
permalink: snapmirror/task_resuming_a_failed_snapmirror_transfer_transition.html 
sidebar: sidebar 
keywords: ontap, 7, mode, resume, failed, snapmirror, baseline, transfer, transition 
summary: Durante la transición, las transferencias básicas de SnapMirror pueden fallar debido a una serie de motivos, como la pérdida de conectividad de red, la transferencia se ha anulado o la conmutación por error de la controladora. Tras rectificar la causa de un fallo, puede reanudar las transferencias de SnapMirror si hay disponible un punto de comprobación de reinicio. 
---
= Reanudación de una transferencia básica de SnapMirror con fallos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante la transición, las transferencias básicas de SnapMirror pueden fallar debido a una serie de motivos, como la pérdida de conectividad de red, la transferencia se ha anulado o la conmutación por error de la controladora. Tras rectificar la causa de un fallo, puede reanudar las transferencias de SnapMirror si hay disponible un punto de comprobación de reinicio.

Si no está disponible el punto de comprobación de reinicio para la transferencia básica, debe eliminar y volver a crear el volumen, restablecer la relación de SnapMirror e iniciar la transición de nuevo.

.Pasos
. Desde el clúster de destino, utilice el `snapmirror show` con el `-snapshot-checkpoint` parámetro para ver el estado de la transferencia de línea de base y el punto de comprobación de reinicio.
+
[listing]
----
cluster2::> snapmirror show -destination-path dest_vserver:vol3 -fields snapshot-checkpoint
source-path          destination-path snapshot-checkpoint
-------------------- ---------------- -------------------
src_system:vol3    dest_vserver:vol3 50MB
----
. Si existe el punto de comprobación de SnapMirror, utilice `snapmirror initialize` comando para reanudar la transferencia básica.
+
[listing]
----
cluster2::> snapmirror initialize -destination-path dest_vserver:vol3
----

