---
permalink: snapmirror/task_transitioning_secondary_volume.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, snapmirror, volume, secondary 
summary: Para realizar la transición de un volumen secundario, es necesario crear una relación de SnapMirror, realizar una transferencia básica, realizar actualizaciones incrementales y configurar una relación de SnapMirror entre el volumen primario de 7-Mode y el volumen secundario de Clustered Data ONTAP. 
---
= La transición de un volumen secundario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para realizar la transición de un volumen secundario, es necesario crear una relación de SnapMirror, realizar una transferencia básica, realizar actualizaciones incrementales y configurar una relación de SnapMirror entre el volumen primario de 7-Mode y el volumen secundario de Clustered Data ONTAP.

Ya se deben configurar el clúster secundario y la máquina virtual de almacenamiento (SVM).

.Pasos
. Copie datos del volumen 7-Mode al volumen de Clustered Data ONTAP:
+
.. Utilice la `snapmirror create` Comando con el tipo de relación como TDP para crear una relación de SnapMirror entre el sistema 7-Mode y la SVM.
+
[listing]
----
sec_cluster::> snapmirror create -source-path sec_system:dst_7_vol -destination-path dst_vserver:dst_c_vol -type TDP
Operation succeeded: snapmirror create the relationship with destination dst_vserver:dst_c_vol.
----
.. Utilice la `snapmirror initialize` comando para iniciar la transferencia de referencia.
+
[listing]
----
sec_cluster::> snapmirror initialize -destination-path dst_vserver:dst_c_vol
Operation is queued: snapmirror initialize of destination dst_vserver:dst_c_vol.
----
.. En función de si desea actualizar el volumen de Clustered Data ONTAP de forma manual o mediante la configuración de una programación de SnapMirror, realice la acción correspondiente:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Actualice las transferencias manualmente
 a| 
... Utilice la `snapmirror update` comando.
+
[listing]
----
sec_cluster::> snapmirror update -destination-path dst_vserver:dst_c_vol
----
... Utilice la `snapmirror show` comando para supervisar el estado de la copia de datos.
+
[listing]
----
sec_cluster::> snapmirror show -destination-path dst_vserver:dst_c_vol
                            Source Path: sec_system:dst_7_vol
                       Destination Path: dst_vserver:dst_c_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
           Number of Successful Updates: 1
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----
... Vaya al paso 3.




 a| 
Realizar transferencias de actualizaciones programadas
 a| 
... Utilice la `job schedule cron create` comando para crear una programación para las transferencias de actualización.
+
[listing]
----
sec_cluster::> job schedule cron create -name 15_minute_sched -minute 15
----
... Utilice la `snapmirror modify` Comando para aplicar la programación a la relación de SnapMirror.
+
[listing]
----
sec_cluster::> snapmirror modify -destination-path dst_vserver:dst_c_vol -schedule 15_minute_sched
----
... Utilice la `snapmirror show` comando para supervisar el estado de la copia de datos.
+
[listing]
----
sec_cluster::> snapmirror show -destination-path dst_vserver:dst_c_vol
                            Source Path: sec_system:dst_7_vol
                       Destination Path: dst_vserver:dst_c_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: 15_minute_sched
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
           Number of Successful Updates: 1
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----


|===


. Si tiene un programa para las transferencias incrementales, realice los pasos siguientes cuando esté listo para realizar la transición:
+
.. Utilice la `snapmirror quiesce` comando para deshabilitar todas las transferencias de actualización futuras.
+
[listing]
----
sec_cluster::> snapmirror quiesce -destination-path dst_vserver:dst_vol
----
.. Utilice la `snapmirror modify` Comando para eliminar la programación de SnapMirror.
+
[listing]
----
sec_cluster::> snapmirror modify -destination-path dst_vserver:dst_vol -schedule ""
----
.. Si colocó en modo inactivo las transferencias de SnapMirror anteriormente, use el `snapmirror resume` Comando para habilitar las transferencias de SnapMirror.
+
[listing]
----
sec_cluster::> snapmirror resume -destination-path dst_vserver:dst_vol
----


. Espere a que finalicen las transferencias continuas entre los volúmenes de 7-Mode y los volúmenes de Clustered Data ONTAP y, a continuación, desconecte el acceso del cliente de los volúmenes de 7-Mode para iniciar la transición.
. Utilice la `snapmirror update` Comando para realizar una actualización final de los datos al volumen de Clustered Data ONTAP.
+
[listing]
----
sec_cluster::> snapmirror update -destination-path dst_vserver:dst_vol
Operation is queued: snapmirror update of destination dst_vserver:dst_vol.
----
. Utilice la `snapmirror show` comando para verificar que la última transferencia se ha realizado correctamente.
. Utilice la `snapmirror break` Comando para romper la relación de SnapMirror entre el volumen secundario de 7-Mode y el volumen secundario de Clustered Data ONTAP.
+
[listing]
----
sec_cluster::> snapmirror break -destination-path dst_vserver:dst_vol
[Job 60] Job succeeded: SnapMirror Break Succeeded
----
. Si sus volúmenes tienen LUN configuradas, en el nivel de privilegios avanzado, utilice el `lun transition 7-mode show` Comando para verificar que se han realizado la transición de las LUN.
+
También puede utilizar el `lun show` Comando en el volumen de Clustered Data ONTAP para ver todas las LUN que se han realizado correctamente la transición.

. Utilice la `snapmirror delete` Comando para eliminar la relación de SnapMirror entre el volumen secundario de 7-Mode y el volumen secundario de Clustered Data ONTAP.
+
[listing]
----
sec_cluster::> snapmirror delete -destination-path dst_vserver:dst_vol
----
. Utilice la `snapmirror release` Comando para eliminar la información de relaciones de SnapMirror del sistema 7-Mode.
+
[listing]
----
system7mode> snapmirror release dataVol20 vs1:dst_vol
----
. Establecer una relación de recuperación ante desastres entre el volumen primario de 7-Mode y el volumen secundario de Clustered Data ONTAP:
+
.. Utilice la `vserver peer transition create` Comando para crear una relación entre iguales de SVM entre el volumen primario de 7-Mode y el volumen secundario de Clustered Data ONTAP.
+
[listing]
----
sec_cluster::> vserver peer transition create -local-vserver dst_vserver -src-filer-name src_system
Transition peering created
----
.. Utilice la `job schedule cron create` Comando para crear una programación de trabajos que coincida con la programación configurada para la relación de SnapMirror en 7-Mode.
+
[listing]
----
sec_cluster::> job schedule cron create -name 15_minute_sched -minute 15
----
.. Utilice la `snapmirror create` Comando para crear una relación de SnapMirror entre el volumen primario de 7-Mode y el volumen secundario de Clustered Data ONTAP.
+
[listing]
----
sec_cluster::> snapmirror create -source-path src_system:src_7_vol -destination-path dst_vserver:dst_c_vol -type TDP -schedule 15_minute_sched
Operation succeeded: snapmirror create the relationship with destination dst_vserver:dst_c_vol.
----
.. Utilice la `snapmirror resync` Comando para volver a sincronizar el volumen secundario de Clustered Data ONTAP.
+
Para una resincronización correcta, debe haber una copia Snapshot común de 7-Mode entre el volumen primario de 7-Mode y el volumen secundario de Clustered Data ONTAP.

+
[listing]
----
sec_cluster::> snapmirror  resync -destination-path dst_vserver:dst_c_vol
----
+
*** Si el clúster de destino ejecuta Data ONTAP 8.3.2 o una versión posterior, debe crear los iGroups necesarios y asignar las LUN manualmente.
*** Si el clúster de destino ejecuta Data ONTAP 8.3.1 o una versión anterior, debe asignar los LUN secundarios manualmente después de completar la transición del almacenamiento de los volúmenes primarios.
*** Debe eliminar la relación entre iguales de SVM entre el sistema 7-Mode secundario y la SVM secundaria cuando todos los volúmenes requeridos en el sistema 7-Mode trasladan a la SVM.
*** Debe eliminar la relación de SnapMirror entre los sistemas principal 7-Mode y los sistemas secundarios 7-Mode.






*Información relacionada*

xref:task_recovering_from_a_failed_lun_transition.adoc[Recuperación de una transición de LUN en caso de error]

xref:task_configuring_a_tcp_window_size_for_snapmirror_relationships.adoc[Configurar un tamaño de ventana TCP para relaciones de SnapMirror]
