---
permalink: snapmirror/task_transitioning_a_stand_alone_volume.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, stand, alone, volume, snapmirror 
summary: La transición de un volumen independiente implica la creación de una relación de SnapMirror, la realización de una transferencia completa, la realización de actualizaciones incrementales, la supervisión de la operación de copia de datos, la ruptura de la relación de SnapMirror y el traslado del acceso de los clientes del volumen de 7-Mode al volumen de Clustered Data ONTAP. 
---
= Realizar la transición de un volumen independiente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La transición de un volumen independiente implica la creación de una relación de SnapMirror, la realización de una transferencia completa, la realización de actualizaciones incrementales, la supervisión de la operación de copia de datos, la ruptura de la relación de SnapMirror y el traslado del acceso de los clientes del volumen de 7-Mode al volumen de Clustered Data ONTAP.

* El clúster y la SVM ya deben estar configurados.
* Debe haber revisado la información sobre cómo prepararse para la transición.
+
xref:task_preparing_for_transition.adoc[Preparación para la transición]



NetApp recomienda aprovisionar el volumen ONTAP de destino para que se ajuste a los atributos del volumen de origen de 7-Mode. Algunos de los atributos que deben coincidir son:

* Volume size: El volumen ONTAP debe tener al menos el tamaño del volumen de 7-Mode.
* Idioma: La configuración del volumen de ONTAP debe coincidir con el valor del volumen de 7-Mode.


La herramienta de transición de 7-Mode aprovisiona automáticamente el volumen ONTAP con atributos que coincidan con el volumen de 7-Mode.

.Pasos
. Copie datos del volumen 7-Mode al volumen de Clustered Data ONTAP:
+
.. Si desea configurar el tamaño de ventana TCP para la relación de SnapMirror entre el sistema 7-Mode y la SVM, cree una política de SnapMirror del tipo `async-mirror` con la `window-size-for-tdp-mirror` opción.
+
Después, debe aplicar esta política a la relación de TDP de SnapMirror entre el sistema 7-Mode y la SVM.

+
Puede configurar el tamaño de la ventana TCP entre 256 KB y 7 MB para mejorar el rendimiento de la transferencia de SnapMirror, de modo que las operaciones de copia de transición se completen más rápido. El valor predeterminado del tamaño de ventana TCP es 2 MB.

+
[listing]
----
cluster1::> snapmirror policy create -vserver vs1 –policy tdp_policy -window-size-for-tdp-mirror 5MB -type async-mirror
----
.. Utilice la `snapmirror create` Comando con el tipo de relación como TDP para crear una relación de SnapMirror entre el sistema 7-Mode y la SVM.
+
Si ha creado una política de SnapMirror para configurar el tamaño de la ventana TCP, debe aplicar la política a esta relación de SnapMirror.

+
[listing]
----
cluster1::> snapmirror create -source-path system7mode:dataVol20 -destination-path vs1:dst_vol -type TDP -policy tdp_policy
Operation succeeded: snapmirror create the relationship with destination vs1:dst_vol.
----
.. Utilice la `snapmirror initialize` comando para iniciar la transferencia de referencia.
+
[listing]
----
cluster1::> snapmirror initialize -destination-path vs1:dst_vol
Operation is queued: snapmirror initialize of destination vs1:dst_vol.
----
.. Utilice la `snapmirror show` comando para supervisar el estado.
+
[listing]
----
cluster1::>snapmirror show -destination-path vs1:dst_vol

                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           **Mirror State: Snapmirrored**
                    Relationship Status: Idle
                File Restore File Count: -
                 File Restore File List: -
                      Transfer Snapshot: -
                      Snapshot Progress: -
                         Total Progress: -
              Network Compression Ratio: -
                    Snapshot Checkpoint: -
                        Newest Snapshot: vs1(4080431166)_dst_vol.1
              Newest Snapshot Timestamp: 10/16 02:49:03
                      Exported Snapshot: vs1(4080431166)_dst_vol.1
            Exported Snapshot Timestamp: 10/16 02:49:03
                                Healthy: true
                       Unhealthy Reason: -
               Constituent Relationship: false
                Destination Volume Node: cluster1-01
                        Relationship ID: 97b205a1-54ff-11e4-9f30-005056a68289
                   Current Operation ID: -
                          Transfer Type: -
                         Transfer Error: -
                       Current Throttle: -
              Current Transfer Priority: -
                     Last Transfer Type: initialize
                    Last Transfer Error: -
                     Last Transfer Size: 152KB
Last Transfer Network Compression Ratio: 1:1
                 Last Transfer Duration: 0:0:6
                     Last Transfer From: system7mode:dataVol20
            Last Transfer End Timestamp: 10/16 02:43:53
                  Progress Last Updated: -
                Relationship Capability: 8.2 and above
                               Lag Time: -
           Number of Successful Updates: 0
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 155648
         Total Transfer Time in Seconds: 6
----
.. En función de si desea actualizar el volumen de Clustered Data ONTAP de forma manual o mediante la configuración de una programación de SnapMirror, realice la acción correspondiente:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Actualice las transferencias manualmente
 a| 
... Utilice la `snapmirror update` comando.
+
[listing]
----
cluster1::> snapmirror update -destination-path vs1:dst_vol
----
... Utilice la `snapmirror show` comando para supervisar el estado de la copia de datos.
+
[listing]
----
cluster1::> snapmirror show -destination-path vs1:dst_vol
                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----
... Vaya al paso 3.




 a| 
Realizar transferencias de actualizaciones programadas
 a| 
... Utilice la `job schedule cron create` comando para crear una programación para las transferencias de actualización.
+
[listing]
----
cluster1::> job schedule cron create -name 15_minute_sched -minute 15
----
... Utilice la `snapmirror modify` Comando para aplicar la programación a la relación de SnapMirror.
+
[listing]
----
cluster1::> snapmirror modify -destination-path vs1:dst_vol -schedule 15_minute_sched
----
... Utilice la `snapmirror show` comando para supervisar el estado de la copia de datos.
+
[listing]
----
cluster1::> snapmirror show -destination-path vs1:dst_vol
                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: 15_minute_sched
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----


|===


. Si tiene un programa para las transferencias incrementales, realice los pasos siguientes cuando esté listo para realizar la transición:
+
.. Utilice la `snapmirror quiesce` comando para deshabilitar todas las transferencias de actualización futuras.
+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs1:dst_vol
----
.. Utilice la `snapmirror modify` Comando para eliminar la programación de SnapMirror.
+
[listing]
----
cluster1::> snapmirror modify -destination-path vs1:dst_vol -schedule ""
----
.. Si colocó en modo inactivo las transferencias de SnapMirror anteriormente, use el `snapmirror resume` Comando para habilitar las transferencias de SnapMirror.
+
[listing]
----
cluster1::> snapmirror resume -destination-path vs1:dst_vol
----


. Espere a que finalicen las transferencias continuas entre los volúmenes de 7-Mode y los volúmenes de Clustered Data ONTAP y, a continuación, desconecte el acceso del cliente de los volúmenes de 7-Mode para iniciar la transición.
. Utilice la `snapmirror update` Comando para realizar una actualización final de los datos al volumen de Clustered Data ONTAP.
+
[listing]
----
cluster1::> snapmirror update -destination-path vs1:dst_vol
Operation is queued: snapmirror update of destination vs1:dst_vol.
----
. Utilice la `snapmirror show` comando para verificar que la última transferencia se ha realizado correctamente.
. Utilice la `snapmirror break` Comando para romper la relación de SnapMirror entre el volumen de 7-Mode y el volumen de Clustered Data ONTAP.
+
[listing]
----
cluster1::> snapmirror break -destination-path vs1:dst_vol
[Job 60] Job succeeded: SnapMirror Break Succeeded
----
. Si sus volúmenes tienen LUN configuradas, en el nivel de privilegios avanzado, utilice el `lun transition 7-mode show` Comando para verificar que se han realizado la transición de las LUN.
+
También puede utilizar el `lun show` Comando en el volumen de Clustered Data ONTAP para ver todas las LUN que se han realizado correctamente la transición.

. Utilice la `snapmirror delete` Comando para eliminar la relación de SnapMirror entre el volumen de 7-Mode y el volumen de Clustered Data ONTAP.
+
[listing]
----
cluster1::> snapmirror delete -destination-path vs1:dst_vol
----
. Utilice la `snapmirror release` Comando para eliminar la información de relaciones de SnapMirror del sistema 7-Mode.
+
[listing]
----
system7mode> snapmirror release dataVol20 vs1:dst_vol
----


Debe eliminar la relación entre iguales de SVM entre el sistema 7-Mode y la SVM cuando todos los volúmenes requeridos en el sistema 7-Mode trasladan a la SVM.

*Información relacionada*

xref:task_resuming_a_failed_snapmirror_transfer_transition.adoc[Reanudación de una transferencia básica de SnapMirror con fallos]

xref:task_recovering_from_a_failed_lun_transition.adoc[Recuperación de una transición de LUN en caso de error]

xref:task_configuring_a_tcp_window_size_for_snapmirror_relationships.adoc[Configurar un tamaño de ventana TCP para relaciones de SnapMirror]
