---
permalink: snapmirror/task_recovering_from_a_disaster_at_7_mode_site_during_transition.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, snapmirror, recover, disaster, site 
summary: 'Si ha establecido una relación \(DR\) de recuperación ante desastres de SnapMirror entre el volumen primario de 7-Mode y el volumen secundario de Clustered Data ONTAP y si se produce un desastre en el sitio primario de 7-Mode, puede dirigir el acceso de los clientes al volumen secundario de Clustered Data ONTAP. Después de que el volumen primario de 7-Mode se ponga en línea de nuevo, debe realizar pasos adicionales para redirigir a los clientes al volumen primario de Clustered Data ONTAP.' 
---
= Recuperación ante desastres en el sitio de 7-Mode durante la transición
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ha establecido una relación de recuperación ante desastres (DR) de SnapMirror entre el volumen primario de 7-Mode y el volumen secundario de Clustered Data ONTAP y si se produce un desastre en la ubicación principal de 7-Mode, puede dirigir al acceso de los clientes al volumen secundario de Clustered Data ONTAP. Después de que el volumen primario de 7-Mode se ponga en línea de nuevo, debe realizar pasos adicionales para redirigir a los clientes al volumen primario de Clustered Data ONTAP.

Para conservar los datos que se escriben en el volumen secundario de Clustered Data ONTAP después del desastre, debe realizar la transición del volumen primario de 7-Mode después de que el volumen primario de 7-Mode vuelva a estar en línea y establecer una relación de SnapMirror entre los volúmenes primario y secundario de Clustered Data ONTAP. A continuación, puede redirigir los clientes a los volúmenes primarios de Clustered Data ONTAP.

No se admite la resincronización de SnapMirror de los volúmenes de Clustered Data ONTAP a los volúmenes de 7-Mode. Por lo tanto, si establece la relación de recuperación ante desastres entre el volumen primario de 7-Mode y el volumen secundario de Clustered Data ONTAP después del desastre, se perderán todos los datos escritos en la Clustered Data ONTAP secundaria.
